import json

DM = 'Checklist items in this family must be re-verified across authenticated and unauthenticated contexts.'
def fam(id_, category, title, summary, items, dont_miss):
    assert all(len(entry) >= 25 for entry in dont_miss), (id_, [e for e in dont_miss if len(e) < 25])
    return {"id": id_, "category": category, "title": title, "summary": summary, "items": items, "dont_miss": dont_miss}

F = []
A = F.append

# ---------------- reconnaissance (38) ----------------
A(fam('recon-discovery-indexing','reconnaissance','Discovery & search indexing','Publicly indexed assets, certificate transparency, robots, sitemaps, and well-known resources.',['WAPT-RECON-001','WAPT-RECON-002','WAPT-RECON-008','WAPT-RECON-009','WAPT-RECON-010'],[DM,'Check certificate transparency logs for historical and current hostnames, not only live certificates','Treat robots and sitemap entries as leads; verify every candidate against the live application','Review well-known resources for security contacts and identity metadata']))
A(fam('recon-dns-hosting','reconnaissance','DNS, hosting & non-production','Authoritative records, resolved boundaries, approved ports, non-production hostnames, and dangling references.',['WAPT-RECON-003','WAPT-RECON-004','WAPT-RECON-005','WAPT-RECON-030','WAPT-RECON-038'],[DM,'Record mail, alias, and delegation records alongside A and CNAME entries','Correlate every resolved address with the approved hosting boundary before probing','Reconcile admin, dev, staging, and preview hostnames with scope and ownership','Identify dangling CNAME and NS targets without ever claiming them']))
A(fam('recon-server-tls','reconnaissance','Server & TLS fingerprinting','Web-server hypotheses and TLS certificate relationships from response characteristics.',['WAPT-RECON-006','WAPT-RECON-007'],[DM,'Rate server fingerprints by confidence instead of trusting a single header','Treat certificate names as endpoint relationships, not automatic scope']))
A(fam('recon-app-routing','reconnaissance','Applications & routing','Distinct applications behind hostnames, base paths, virtual hosts, and default-site behavior.',['WAPT-RECON-011','WAPT-RECON-012'],[DM,'Separate tenant portals, management surfaces, and route roots sharing one hostname','Compare approved Host values for routing and default-site behavior']))
A(fam('recon-content-javascript','reconnaissance','Content & JavaScript extraction','HTML comments, metadata, first-party script route extraction, and source-map classification.',['WAPT-RECON-013','WAPT-RECON-014','WAPT-RECON-015'],[DM,'Record hidden fields and disabled markup as reachable-attack-surface leads','Extract routes and service origins from script literals and request constructors','Classify source maps without treating readable client code as a finding']))
A(fam('recon-surface-mapping','reconnaissance','Surface mapping','Forms, parameters, routes, methods, and multi-step workflow state transitions.',['WAPT-RECON-016','WAPT-RECON-017','WAPT-RECON-018','WAPT-RECON-019'],[DM,'Inventory constraints, submission targets, and encodings per form','Deduplicate parameters across URL, body, headers, and cookies with example values','Distinguish read, mutation, upload, authentication, and administrative routes','Document valid workflow states, prerequisites, and rollback paths']))
A(fam('recon-identity-accounts','reconnaissance','Identity & account flows','Authentication, reauthentication, step-up entry points, and account-lifecycle flows.',['WAPT-RECON-020','WAPT-RECON-021'],[DM,'Catalog every route that establishes, refreshes, elevates, or re-verifies identity','Map registration, invitation, recovery, and account-change flows before targeting them']))
A(fam('recon-api-realtime','reconnaissance','API & realtime discovery','API roots, documentation, GraphQL endpoints, and WebSocket or SSE channels.',['WAPT-RECON-022','WAPT-RECON-023','WAPT-RECON-024','WAPT-RECON-025'],[DM,'Build the API inventory from observed traffic before consulting documentation','Compare owner-published schemas against actually deployed operations','Confirm GraphQL transport modes, content types, and subscription channels','Catalog WebSocket handshake URLs, subprotocols, and authentication transport']))
A(fam('recon-frameworks-intermediaries','reconnaissance','Frameworks & intermediaries','Server-side frameworks, packaged applications, CDNs, proxies, and edge-versus-origin behavior.',['WAPT-RECON-026','WAPT-RECON-027','WAPT-RECON-028','WAPT-RECON-029'],[DM,'Fingerprint frameworks with corroborating cookies, headers, paths, and error forms','Identify packaged applications and CMS versions with multiple non-invasive markers','Model request hops and trust boundaries across proxies, CDNs, and application tiers','Compare edge and suspected origin behavior without bypassing scope']))
A(fam('recon-third-party-browser','reconnaissance','Third-party & browser state','External script and identity dependencies plus browser storage and configuration namespaces.',['WAPT-RECON-031','WAPT-RECON-032'],[DM,'Document external origins that receive data, execute in the page, or provide identity','Catalog localStorage, IndexedDB, and cache namespaces used by the application']))
A(fam('recon-entry-points','reconnaissance','Entry points & error families','Upload, search, and reporting entry points plus error-response classification.',['WAPT-RECON-033','WAPT-RECON-034','WAPT-RECON-035'],[DM,'Include import, export, preview, and conversion routes in the entry-point inventory','Map search, filtering, sorting, and reporting inputs before testing them','Classify error families to guide later differentiation between vulnerable and benign']))
A(fam('recon-attack-surface-register','reconnaissance','Attack-surface register','Test matrices and the confirmed in-scope register that anchors the engagement.',['WAPT-RECON-036','WAPT-RECON-037'],[DM,'Link test identities to roles, tenants, ownership states, and reachable functions','Keep the attack-surface register updated as scope changes during the engagement']))

# ---------------- http (26) ----------------
A(fam('http-methods','http','HTTP methods','Unsupported-method rejection, safe-method side effects, and method override handling.',['WAPT-HTTP-001','WAPT-HTTP-002','WAPT-HTTP-003'],[DM,'Check unsupported methods on every route, not just the documented endpoints','Confirm GET, HEAD, and OPTIONS never trigger security-sensitive state changes','Test override headers and body parameters for unauthorized verb selection']))
A(fam('http-content-encoding','http','Content types & encoding','Declared media types, accurate responses, and MIME-sniffing boundaries.',['WAPT-HTTP-004','WAPT-HTTP-005','WAPT-HTTP-006'],[DM,'Send bodies under undeclared, ambiguous, or conflicting Content-Type values','Compare declared media types and charsets against actual response bytes','Test whether sniffing can reinterpret user-controlled responses as active content']))
A(fam('http-path-parameter-normalization','http','Path & parameter normalization','Dot segments, repeated separators, duplicate parameters, and decode boundaries.',['WAPT-HTTP-007','WAPT-HTTP-008','WAPT-HTTP-009'],[DM,'Probe dot segments, repeated separators, case, and trailing delimiters','Check whether path or parameter decoding happens more than once','Resolve duplicate parameters consistently across every hop']))
A(fam('http-target-authority','http','Target & host authority','Absolute-form targets, Host versus :authority, and forwarding-header trust.',['WAPT-HTTP-010','WAPT-HTTP-011','WAPT-HTTP-012'],[DM,'Send absolute-form and authority-form targets and observe routing changes','Compare HTTP/1 Host and HTTP/2 authority validation for the same route','Verify forwarding headers only influence state when an authenticated proxy sent them']))
A(fam('http-redirects-https','http','Redirects & HTTPS','User-controlled redirects and plaintext entry paths.',['WAPT-HTTP-013','WAPT-HTTP-014'],[DM,'Test redirect parameters, paths, and headers against attacker-controlled origins','Map plaintext entry paths and verify canonical HTTPS redirection without mixed content']))
A(fam('http-cors','http','CORS','Origin allowlists, credentialed access, opaque origins, preflights, and exposed headers.',['WAPT-HTTP-015','WAPT-HTTP-016','WAPT-HTTP-017','WAPT-HTTP-018','WAPT-HTTP-019'],[DM,'Distinguish reflected origins from exact allowlist decisions','Test credentialed CORS reads with ambient cookies and HTTP authentication','Reach sensitive operations through simple requests that skip preflight','Review Access-Control-Expose-Headers for secret-bearing names']))
A(fam('http-caching','http','Caching','Persistent caches, shared-cache partitioning, cache keys, and Vary metadata.',['WAPT-HTTP-020','WAPT-HTTP-021','WAPT-HTTP-022','WAPT-HTTP-023'],[DM,'Verify sensitive representations are not stored in persistent or shared caches','Test whether a CDN or reverse proxy can serve one user representation to another','Probe unkeyed query fields, headers, and cookies for cache poisoning','Check Vary distinguishes representations shaped by safe request headers']))
A(fam('http-conditional-advanced','http','Conditional & protocol translation','Conditional and range requests, compression oracles, and framing translation.',['WAPT-HTTP-024','WAPT-HTTP-025','WAPT-HTTP-026'],[DM,'Reauthorize If-None-Match, If-Modified-Since, and Range requests for protected resources','Assess compression oracles where reflected secrets share compressed responses','Verify edge-to-origin protocol translation rejects ambiguous message framing']))

# ---------------- session-management (28) ----------------
A(fam('sess-token-inventory','session-management','Token inventory & transport','Session-token discovery and URL or referrer exposure.',['WAPT-SESS-001','WAPT-SESS-018'],[DM,'Inventory cookies, headers, body fields, and client stores that carry session state','Check paths, queries, redirects, browser history, and Referer for token leakage']))
A(fam('sess-cookie-attributes','session-management','Cookie attributes','Secure, HttpOnly, SameSite, Domain, Path, and persistent lifetime.',['WAPT-SESS-002','WAPT-SESS-003','WAPT-SESS-004','WAPT-SESS-005','WAPT-SESS-006'],[DM,'Verify Secure on every authentication-bearing cookie','Confirm HttpOnly unless script access is genuinely required','Choose SameSite against the real cross-site authentication flow','Minimize Domain and Path scope to avoid sibling-host exposure','Bound persistent cookie lifetime to the documented server-side risk policy']))
A(fam('sess-token-properties','session-management','Token properties','Entropy and plaintext sensitivity of client-visible session values.',['WAPT-SESS-007','WAPT-SESS-008'],[DM,'Verify session identifiers are unique and unpredictable across issuance events','Check session values for usernames, roles, internal IDs, or secrets']))
A(fam('sess-fixation-rotation','session-management','Fixation & rotation','Pre-authentication fixation, post-auth rotation, and privilege-change rotation.',['WAPT-SESS-009','WAPT-SESS-010','WAPT-SESS-011'],[DM,'Confirm attacker-chosen pre-login identifiers never survive authentication','Verify login replaces and invalidates every pre-authentication token','Rotate session authority after role elevation, impersonation, and step-up']))
A(fam('sess-lifecycle-logout','session-management','Lifecycle & logout','Concurrency, logout invalidation, revocation, idle and absolute timeouts, and server-side expiry.',['WAPT-SESS-012','WAPT-SESS-013','WAPT-SESS-014','WAPT-SESS-015','WAPT-SESS-016','WAPT-SESS-017'],[DM,'Enforce concurrent-session limits consistent with account risk','Verify captured tokens stop working after logout','Confirm users can review and revoke other active sessions','Test idle timeout from server-observed activity, not client timers','Verify absolute maximum lifetime survives continuous refresh activity']))
A(fam('sess-identity-changes','session-management','Identity & account changes','Disablement, deletion, password or factor changes, and account switching.',['WAPT-SESS-020','WAPT-SESS-021','WAPT-SESS-024'],[DM,'Confirm disabled or deleted identities lose all sessions and persistent tokens','Offer session termination after password or factor changes','Verify logout/login and account switching leaves no prior identity state']))
A(fam('sess-puzzling-isolation','session-management','Puzzling & isolation','Multiple token names, sibling-application isolation, and explicit session creation.',['WAPT-SESS-022','WAPT-SESS-023','WAPT-SESS-026'],[DM,'Swap, omit, and mix parallel session values to select another identity','Verify tokens from one application are rejected by sibling applications','Confirm cross-site navigation cannot silently create application sessions']))
A(fam('sess-federation-distribution','session-management','Federation & distribution','Coordinated logout, revocation propagation, and refresh-token family replay.',['WAPT-SESS-025','WAPT-SESS-027','WAPT-SESS-028'],[DM,'Coordinate relying-party and identity-provider logout semantics','Verify revocation reaches APIs, gateways, workers, and regional services','Detect replay of rotated refresh or persistent token families']))
A(fam('sess-client-storage','session-management','Client storage','Reusable session authority in script-readable storage.',['WAPT-SESS-019'],[DM,'Evaluate localStorage and IndexedDB bearer tokens against the XSS surface and lifetime']))

# ---------------- injection (55) ----------------
A(fam('inj-sql','injection','SQL injection','Detection, confirmation, identifiers, second-order, ORM, bulk, and asynchronous SQL paths.',['WAPT-INJ-001','WAPT-INJ-002','WAPT-INJ-003','WAPT-INJ-004','WAPT-INJ-005','WAPT-INJ-006','WAPT-INJ-007','WAPT-INJ-008'],[DM,'Confirm every differential with paired predicates, never a single error','Test ORDER BY, identifiers, and stored-value paths beyond string positions','Verify parameterization across bulk, array, and asynchronous report inputs']))
A(fam('inj-nosql','injection','NoSQL injection','Operator injection, auth bypass, blind predicates, server-side JavaScript, pipelines, and second-order fragments.',['WAPT-INJ-009','WAPT-INJ-010','WAPT-INJ-011','WAPT-INJ-012','WAPT-INJ-013','WAPT-INJ-014'],[DM,'Probe operator objects in structured JSON bodies','Pair blind response predicates before concluding NoSQL injection','Test aggregation and projection pipelines plus stored query fragments']))
A(fam('inj-ldap','injection','LDAP injection','Filters in authentication lookups, directory searches, and DN construction.',['WAPT-INJ-015','WAPT-INJ-016','WAPT-INJ-017'],[DM,'Test authentication lookups and directory search filters separately','Escape distinguished-name construction independently from filters']))
A(fam('inj-xml-xpath','injection','XML, XPath & entities','Predicate injection, structure injection, external entities, DTDs, and XInclude.',['WAPT-INJ-018','WAPT-INJ-019','WAPT-INJ-020','WAPT-INJ-021','WAPT-INJ-022','WAPT-INJ-023'],[DM,'Pair XPath predicates to confirm node-set differences','Test element and attribute value positions for structure injection','Verify external entities, parameter entities, and XInclude are all disabled']))
A(fam('inj-command','injection','Command injection','Separators, blind timing, argument injection, filenames, workers, and environment influence.',['WAPT-INJ-024','WAPT-INJ-025','WAPT-INJ-026','WAPT-INJ-027','WAPT-INJ-028','WAPT-INJ-029'],[DM,'Use inert output markers before timing-based confirmation','Test argument injection without shell metacharacters','Probe filenames, upload metadata, and asynchronous worker paths','Constrain environment and executable-path influence']))
A(fam('inj-template-expression','injection','Template & expression injection','SSTI detection, context classification, stored and blind variants, sandboxes, includes, and dynamic evaluation.',['WAPT-INJ-030','WAPT-INJ-031','WAPT-INJ-032','WAPT-INJ-033','WAPT-INJ-034','WAPT-INJ-035','WAPT-INJ-036','WAPT-INJ-037','WAPT-INJ-038'],[DM,'Classify the template context before choosing syntax','Test stored and blind template paths with controlled callbacks','Probe sandbox boundaries without attempting host escape','Cover expression-language and dynamic-evaluation equivalents']))
A(fam('inj-header-log','injection','Header, log & mail injection','CRLF into headers and redirects, log sanitization, and email header injection.',['WAPT-INJ-039','WAPT-INJ-040','WAPT-INJ-041','WAPT-INJ-042'],[DM,'Test response-header and redirect Location CRLF positions','Sanitize untrusted values before structured logging','Verify generated email messages cannot inject additional headers']))
A(fam('inj-parameter-pollution','injection','Parameter pollution','Duplicate-parameter rules and cross-source pollution.',['WAPT-INJ-043','WAPT-INJ-044'],[DM,'Apply one duplicate-parameter rule across security controls and parsing','Test cross-source pollution between query, body, cookies, and headers']))
A(fam('inj-export-host','injection','Export & host injection','Spreadsheet formulas, CSV quoting, Host validation, link origins, cache keys, and forwarded values.',['WAPT-INJ-045','WAPT-INJ-046','WAPT-INJ-047','WAPT-INJ-048','WAPT-INJ-049','WAPT-INJ-050'],[DM,'Neutralize spreadsheet formulas in exported user data','Preserve CSV boundaries and quoting during export','Validate Host before routing and security decisions','Build password and invitation links from a canonical origin','Ignore untrusted forwarded host and scheme values']))
A(fam('inj-mail-misc','injection','Mail, regex & SSI','SMTP and IMAP injection, regex injection and ReDoS, and server-side includes.',['WAPT-INJ-051','WAPT-INJ-052','WAPT-INJ-053','WAPT-INJ-054','WAPT-INJ-055'],[DM,'Test recipient fields for SMTP command injection','Escape untrusted text embedded in regular expressions','Bound catastrophic backtracking with long adversarial inputs']))

# ---------------- xss (30) ----------------
A(fam('xss-reflected-stored','xss','Reflected & stored XSS','Input classification, stored user content, and blind stored payloads in privileged views.',['WAPT-XSS-001','WAPT-XSS-002','WAPT-XSS-003'],[DM,'Classify the reflection context before choosing a payload','Confirm stored XSS with an isolated observer account','Detect blind stored variants in privileged review surfaces']))
A(fam('xss-dom-storage','xss','DOM & storage XSS','Location sources, postMessage, and browser-storage values reaching executable sinks.',['WAPT-XSS-004','WAPT-XSS-005','WAPT-XSS-006'],[DM,'Trace URL-derived flows from location sources to executable sinks','Validate postMessage origin and payload before DOM insertion','Keep browser-storage values out of executable DOM sinks']))
A(fam('xss-sink-source','xss','Sinks & sources','API and realtime message encoding, dangerous HTML and JavaScript sinks, and URL schemes.',['WAPT-XSS-007','WAPT-XSS-008','WAPT-XSS-009','WAPT-XSS-010','WAPT-XSS-011'],[DM,'Encode API and WebSocket message data at the final DOM sink','Remove innerHTML-style sinks for untrusted values','Reject unsafe URL schemes in navigation and resource sinks']))
A(fam('xss-sanitization','xss','Sanitization','Configuration bypasses, mutation XSS, rich text, SVG, and Markdown transformations.',['WAPT-XSS-012','WAPT-XSS-013','WAPT-XSS-014','WAPT-XSS-015','WAPT-XSS-016'],[DM,'Test sanitizer configuration and nesting bypasses','Detect mutation XSS after browser reparsing','Constrain active content in user-supplied SVG','Sanitize Markdown and rich-text output on the trusted boundary']))
A(fam('xss-framework-template','xss','Frameworks & templates','Framework escape hatches, client-side templates, and JSONP.',['WAPT-XSS-017','WAPT-XSS-018','WAPT-XSS-020'],[DM,'Keep framework escape hatches away from untrusted content','Prevent client-side template injection reaching script execution','Validate JSONP callback names or remove JSONP entirely']))
A(fam('xss-upload-encoding','xss','Uploads & encoding','Active upload files and character-encoding normalization.',['WAPT-XSS-019','WAPT-XSS-021'],[DM,'Serve uploaded active files outside the application origin','Normalize character encoding before validation and output']))
A(fam('xss-defenses-evidence','xss','Defenses & evidence','CSP as impact reduction, Trusted Types, and evidence hygiene.',['WAPT-XSS-022','WAPT-XSS-029','WAPT-XSS-030'],[DM,'Treat CSP as impact reduction, never as an XSS substitute','Enforce Trusted Types without permissive bypass policies','Demonstrate impact without collecting sensitive data']))
A(fam('xss-boundaries-edges','xss','Boundaries & edge cases','WAF bypass, self-XSS, extension noise, dangling markup, base injection, and script gadgets.',['WAPT-XSS-023','WAPT-XSS-024','WAPT-XSS-025','WAPT-XSS-026','WAPT-XSS-027','WAPT-XSS-028'],[DM,'Treat WAF bypass as validation of a real sink','Require a realistic delivery path for self-XSS','Exclude browser extensions and tooling from evidence','Evaluate script gadgets only after confirmed data flow']))

# ---------------- csrf (18) ----------------
A(fam('csrf-inventory','csrf','CSRF inventory','Sensitive actions using ambient browser credentials.',['WAPT-CSRF-001'],[DM,'Inventory state-changing actions reachable with ambient cookies across methods']))
A(fam('csrf-token-validation','csrf','Token validation','Missing, invalid, session-bound, action-bound, and leaking anti-CSRF tokens.',['WAPT-CSRF-002','WAPT-CSRF-003','WAPT-CSRF-004','WAPT-CSRF-005','WAPT-CSRF-006'],[DM,'Reject missing, invalid, and attacker-supplied tokens','Bind tokens to the session and, where risk requires, the action','Verify tokens are unpredictable and never leak cross-origin']))
A(fam('csrf-origin-referer','csrf','Origin & Referer','Origin validation and privacy-aware Referer fallback.',['WAPT-CSRF-007','WAPT-CSRF-008'],[DM,'Validate Origin on sensitive browser requests','Treat Referer as a fallback with its privacy limits in mind']))
A(fam('csrf-samesite-media','csrf','SameSite & media types','SameSite behavior and simple-request media types for JSON-only operations.',['WAPT-CSRF-009','WAPT-CSRF-010'],[DM,'Account for actual SameSite cookie behavior in CSRF decisions','Reject simple-request media types for JSON-only sensitive operations']))
A(fam('csrf-method-navigation','csrf','Methods & navigation','Method overrides and cross-site GET state changes.',['WAPT-CSRF-011','WAPT-CSRF-012'],[DM,'Keep method overrides from bypassing CSRF controls','Prevent state changes through cross-site GET navigation']))
A(fam('csrf-login-uploads','csrf','Login, logout, uploads & GraphQL','Login CSRF, forced logout, multipart actions, and GraphQL mutations.',['WAPT-CSRF-013','WAPT-CSRF-014','WAPT-CSRF-015','WAPT-CSRF-016'],[DM,'Prevent login CSRF and attacker-account session planting','Verify logout requires the user intention it claims','Protect multipart and file-processing actions','Test GraphQL mutations over simple cross-site transports']))
A(fam('csrf-boundaries','csrf','Boundaries','CORS-versus-CSRF distinction and step-up for critical actions.',['WAPT-CSRF-017','WAPT-CSRF-018'],[DM,'Separate response-read permissions from request-transmission impact','Require step-up or transaction binding for critical cross-site actions']))

# ---------------- graphql (15) ----------------
A(fam('gql-discovery-introspection','graphql','Discovery & introspection','Endpoint and transport inventory, introspection, and schema reconciliation.',['WAPT-GQL-001','WAPT-GQL-002','WAPT-GQL-003'],[DM,'Inventory HTTP, multipart, batch, and subscription transports','Restrict production introspection to the intended consumer model','Reconcile schemas from clients and traffic without reporting names as findings']))
A(fam('gql-authorization','graphql','Authorization','Object, field, mutation, and function authorization in resolvers.',['WAPT-GQL-004','WAPT-GQL-005','WAPT-GQL-006','WAPT-GQL-007'],[DM,'Swap node IDs and nested arguments across accounts and tenants','Select sensitive fields hidden from normal client queries','Bind protected fields like role, owner, price, and status per caller','Invoke privileged mutations from lower-privilege contexts']))
A(fam('gql-depth-cost','graphql','Depth & cost','Query depth, cost analysis, and alias-based bypasses.',['WAPT-GQL-008','WAPT-GQL-009','WAPT-GQL-010'],[DM,'Bound recursive traversal and resolver fan-out','Count aliases and repeated fields toward cost limits']))
A(fam('gql-batch-pagination','graphql','Batching & pagination','Batch operations and connection traversal limits.',['WAPT-GQL-011','WAPT-GQL-012'],[DM,'Apply limits per batched operation, not per request','Bound first, last, limit, cursor, and nested connection arguments']))
A(fam('gql-transport-boundaries','graphql','Transport boundaries','CSRF over alternate encodings, subscription authorization, and error hygiene.',['WAPT-GQL-013','WAPT-GQL-014','WAPT-GQL-015'],[DM,'Test mutations over GET, form, and text/plain transports','Authorize subscriptions at subscribe and event time','Return errors without secrets or unauthorized data']))

# ---------------- jwt (18) ----------------
A(fam('jwt-signature-algorithm','jwt','Signature & algorithm','Signature verification, algorithm allowlists, none, confusion, and HMAC secrets.',['WAPT-JWT-001','WAPT-JWT-002','WAPT-JWT-003','WAPT-JWT-004','WAPT-JWT-005'],[DM,'Verify every signature before trusting claims','Allowlist algorithms from server configuration only','Reject none and empty-signature tokens','Prevent symmetric-asymmetric key confusion','Use strong random HMAC secrets']))
A(fam('jwt-claim-validation','jwt','Claim validation','Issuer, audience, token type, expiry, and not-before enforcement.',['WAPT-JWT-006','WAPT-JWT-007','WAPT-JWT-008','WAPT-JWT-009'],[DM,'Validate issuer against a configured trust set','Validate audience per receiving service','Keep ID, access, refresh, and reset tokens from being interchangeable','Enforce expiry and not-before outside a small clock tolerance']))
A(fam('jwt-identity-privilege','jwt','Identity & privilege claims','Subject and tenant binding plus role and privilege claim trust.',['WAPT-JWT-010','WAPT-JWT-011'],[DM,'Bind subject and tenant claims to authoritative identity','Ignore client-modified roles, scopes, and admin flags']))
A(fam('jwt-key-management','jwt','Key management','kid lookup, external keys, and rotation fallback.',['WAPT-JWT-012','WAPT-JWT-013','WAPT-JWT-014'],[DM,'Constrain kid lookup to trusted key identifiers','Reject attacker-controlled jku, x5u, and embedded JWKs','Handle rotation without accepting unverified tokens']))
A(fam('jwt-replay-lifecycle','jwt','Replay & lifecycle','Token replay and refresh-token family rotation.',['WAPT-JWT-015','WAPT-JWT-016'],[DM,'Limit replay according to token risk and channel','Rotate and revoke refresh-token families on reuse detection']))
A(fam('jwt-transport-storage','jwt','Transport & storage','URL and log leakage plus browser storage decisions.',['WAPT-JWT-017','WAPT-JWT-018'],[DM,'Keep bearer tokens out of URLs, logs, and referrers','Match browser storage to token authority and lifetime']))

# ---------------- oauth-sso-saml (22) ----------------
A(fam('oauth-redirect-state','oauth-sso-saml','OAuth redirect & state','Redirect URI matching, state binding, and OIDC nonce validation.',['WAPT-OAUTH-001','WAPT-OAUTH-002','WAPT-OAUTH-003'],[DM,'Match redirect URIs exactly per client','Bind authorization responses to the initiating browser transaction','Validate OIDC nonce against the initiating session']))
A(fam('oauth-code-flow','oauth-sso-saml','Authorization code flow','PKCE, code consumption, and authorization-server mix-up.',['WAPT-OAUTH-004','WAPT-OAUTH-005','WAPT-OAUTH-006'],[DM,'Require PKCE for authorization-code clients','Consume codes once within a short lifetime','Prevent multi-provider clients from confusing issuers']))
A(fam('oauth-response-handling','oauth-sso-saml','Response handling','Parameter pollution and code/token leakage channels.',['WAPT-OAUTH-007','WAPT-OAUTH-008'],[DM,'Reject duplicated code, state, issuer, scope, and redirect parameters','Keep codes and tokens out of Referer, history, logs, and analytics']))
A(fam('oauth-scopes-grants','oauth-sso-saml','Scopes & grants','Scope and consent limits plus deprecated grant rejection.',['WAPT-OAUTH-009','WAPT-OAUTH-010'],[DM,'Constrain scopes and consent to intended access','Reject implicit and password grants bypassing code-flow protections']))
A(fam('oauth-tokens-clients','oauth-sso-saml','Tokens & clients','Refresh-token protections, audience validation, and client-credential security.',['WAPT-OAUTH-011','WAPT-OAUTH-012','WAPT-OAUTH-013'],[DM,'Rotate and sender-constrain refresh tokens','Validate audience and scope on every resource server','Keep confidential-client secrets out of browsers and mobile packages']))
A(fam('oauth-navigation','oauth-sso-saml','Client navigation','Open-redirect chains through OAuth clients.',['WAPT-OAUTH-014'],[DM,'Test registered callbacks and post-login routes for authorization-material forwarding']))
A(fam('saml-signatures','oauth-sso-saml','SAML signatures','Assertion signatures and XML signature wrapping.',['WAPT-OAUTH-015','WAPT-OAUTH-016'],[DM,'Validate response and assertion signatures before use','Detect signature wrapping where one element is validated and another consumed']))
A(fam('saml-binding-time','oauth-sso-saml','SAML binding & time','Audience, recipient, destination, issuer, replay, and time conditions.',['WAPT-OAUTH-017','WAPT-OAUTH-018','WAPT-OAUTH-019'],[DM,'Validate audience, recipient, destination, and issuer','Bind responses to requests and reject replays','Enforce NotBefore, NotOnOrAfter, and subject-confirmation expiry']))
A(fam('saml-state-attributes','oauth-sso-saml','SAML state & attributes','RelayState navigation and attribute-driven role mapping.',['WAPT-OAUTH-020','WAPT-OAUTH-021'],[DM,'Constrain RelayState and post-SSO navigation','Constrain attributes that map roles, groups, tenants, and accounts']))
A(fam('sso-logout-fallback','oauth-sso-saml','Logout & fallback','Coordinated logout and local fallback beside federated assurance.',['WAPT-OAUTH-022'],[DM,'Coordinate IdP logout, SP logout, and stale federation sessions','Prevent local fallback from bypassing SSO assurance']))

# ---------------- ssrf (15) ----------------
A(fam('ssrf-detection','ssrf','SSRF detection','Confirmation with controlled callbacks and blind detection.',['WAPT-SSRF-001','WAPT-SSRF-002'],[DM,'Confirm fetches with unique controlled callbacks','Detect blind fetches through asynchronous and out-of-band evidence']))
A(fam('ssrf-allowlists-schemes','ssrf','Allowlists & schemes','Scheme allowlists and parsed host allowlists.',['WAPT-SSRF-003','WAPT-SSRF-004'],[DM,'Allowlist URL schemes before any fetch','Validate hosts with parsed exact allowlists, not substrings']))
A(fam('ssrf-address-normalization','ssrf','Address normalization','IP representation normalization and parser differentials.',['WAPT-SSRF-005','WAPT-SSRF-010'],[DM,'Normalize decimal, hex, octal, shortened, and IPv4-mapped addresses','Test backslash and encoding differentials between validators and clients']))
A(fam('ssrf-redirects-resolution','ssrf','Redirects & resolution','Redirect revalidation and connection-time address validation.',['WAPT-SSRF-006','WAPT-SSRF-007'],[DM,'Revalidate every redirect target','Validate resolved addresses at connection time against rebinding']))
A(fam('ssrf-metadata-egress','ssrf','Metadata & egress','Cloud metadata destinations, port constraints, and egress backstops.',['WAPT-SSRF-008','WAPT-SSRF-009','WAPT-SSRF-015'],[DM,'Block provider metadata and workload-identity destinations at egress','Constrain fetch ports and internal service reach','Enforce least-privilege network egress as a backstop']))
A(fam('ssrf-response-consumers','ssrf','Response & consumers','Response exposure limits and document renderer fetches.',['WAPT-SSRF-011','WAPT-SSRF-013'],[DM,'Limit response bodies, headers, redirects, and timing exposure','Constrain PDF, image, screenshot, and markup renderers that fetch URLs']))
A(fam('ssrf-webhooks-second-order','ssrf','Webhooks & second-order','Webhook binding and stored-URL re-fetching.',['WAPT-SSRF-012','WAPT-SSRF-014'],[DM,'Bind webhook delivery to registered destinations per tenant','Trace stored URLs fetched later by other workers']))

# ---------------- request-smuggling (14) ----------------
A(fam('smug-planning-controls','request-smuggling','Planning & controls','Topology mapping and framing baseline.',['WAPT-SMUG-001','WAPT-SMUG-002'],[DM,'Map every hop, protocol version, and downgrade path before probing','Establish well-formed framing and connection-reuse controls first']))
A(fam('smug-http1-desync','request-smuggling','HTTP/1 desync','CL.TE, TE.CL, and TE.TE disagreements.',['WAPT-SMUG-003','WAPT-SMUG-004','WAPT-SMUG-005'],[DM,'Detect CL.TE and TE.CL disagreements on isolated routes','Test obfuscated and duplicated Transfer-Encoding normalization']))
A(fam('smug-h2-downgrade','request-smuggling','HTTP/2 downgrade','H2.CL, H2.TE, and header-value injection on downgrade.',['WAPT-SMUG-006','WAPT-SMUG-007','WAPT-SMUG-008'],[DM,'Test Content-Length and Transfer-Encoding downgrade desync','Reject HTTP/2 header values that inject HTTP/1 fields']))
A(fam('smug-confirmation-safety','request-smuggling','Confirmation & safety','Queue-poisoning confirmation without user impact.',['WAPT-SMUG-009'],[DM,'Confirm desync with isolated endpoints and harmless canaries only']))
A(fam('smug-advanced-variants','request-smuggling','Advanced variants','0.CL, client-side, and pause-based desync in isolation.',['WAPT-SMUG-010','WAPT-SMUG-011','WAPT-SMUG-012'],[DM,'Assess 0.CL and early responses only in isolation','Assess client-side desync on dedicated browser-facing connections','Assess pause-based desync only with owner instrumentation']))
A(fam('smug-verification','request-smuggling','Verification','False-positive exclusions and remediation verification.',['WAPT-SMUG-013','WAPT-SMUG-014'],[DM,'Exclude load balancing, retries, caching, and affinity noise','Verify remediation across every protocol hop']))

# ---------------- business-logic (35) ----------------
A(fam('bl-workflow-state','business-logic','Workflow & state','State mapping, skipped steps, out-of-order transitions, replays, and token binding.',['WAPT-BL-001','WAPT-BL-002','WAPT-BL-003','WAPT-BL-004','WAPT-BL-005'],[DM,'Map invariants before mutating workflow transitions','Reject skipped, replayed, and out-of-order steps','Bind workflow tokens to the intended account and object']))
A(fam('bl-pricing-totals','business-logic','Pricing & totals','Ranges, signs, prices, quantities, currency, and recalculated totals.',['WAPT-BL-006','WAPT-BL-007','WAPT-BL-008','WAPT-BL-009','WAPT-BL-010'],[DM,'Validate numeric ranges and signs as business values','Recalculate prices, tax, shipping, fees, and discounts server-side','Bind currency to the trusted price and settlement context']))
A(fam('bl-promotions-stored-value','business-logic','Promotions & stored value','Coupon eligibility and stacking plus gift cards, credits, and points.',['WAPT-BL-011','WAPT-BL-012','WAPT-BL-013'],[DM,'Enforce coupon eligibility, ownership, and stacking limits','Protect stored value against reuse, refund, and transfer abuse']))
A(fam('bl-checkout-payments','business-logic','Checkout & payments','Checkout state, payment binding, refunds, and cancellation windows.',['WAPT-BL-014','WAPT-BL-015','WAPT-BL-016','WAPT-BL-017'],[DM,'Bind checkout completion to verified payment state','Verify amount, currency, merchant, and order binding','Constrain cancellation after irreversible fulfillment']))
A(fam('bl-subscriptions-limits','business-logic','Subscriptions & limits','Trial lifecycle, usage limits, and reset channels.',['WAPT-BL-018','WAPT-BL-019','WAPT-BL-020'],[DM,'Enforce subscription and trial lifecycle rules','Test per-user and global usage limits','Block limit resets through alternate identities or channels']))
A(fam('bl-referrals-approvals','business-logic','Referrals & approvals','Invitation rules, reviewer eligibility, and maker-checker separation.',['WAPT-BL-021','WAPT-BL-022','WAPT-BL-023','WAPT-BL-024'],[DM,'Enforce invitation and referral business rules','Bind approvals to eligible independent reviewers','Reject forged client-side integrity fields']))
A(fam('bl-async-state','business-logic','Asynchronous & state','Callback binding, job scope, retry duplicates, and account prerequisites.',['WAPT-BL-025','WAPT-BL-026','WAPT-BL-027','WAPT-BL-028'],[DM,'Bind asynchronous callbacks to their original transactions','Keep jobs within current account and object state','Prevent duplicate business effects across retries','Validate account-state prerequisites for sensitive flows']))
A(fam('bl-tenant-entitlement','business-logic','Tenant & entitlement','Tenant invariants and plan downgrade confusion.',['WAPT-BL-029','WAPT-BL-030'],[DM,'Enforce tenant-specific business invariants','Prevent plan and entitlement downgrade confusion']))
A(fam('bl-time-inventory','business-logic','Time, inventory & abuse','Server-time windows, hoarding, and abuse through search or notifications.',['WAPT-BL-031','WAPT-BL-032','WAPT-BL-033'],[DM,'Validate time windows with trusted server time','Prevent reservation and inventory hoarding','Detect business abuse across search and notification features']))
A(fam('bl-consent-retest','business-logic','Consent & retest','Consent persistence and adjacent-channel remediation verification.',['WAPT-BL-034','WAPT-BL-035'],[DM,'Preserve consent and disclosure decisions through workflows','Verify business-rule fixes across adjacent channels']))

# ---------------- race-conditions (12) ----------------
A(fam('race-value-payment','race-conditions','Value & payment races','Duplicate redemption and duplicate payment transactions.',['WAPT-RACE-001','WAPT-RACE-002'],[DM,'Test single-use value redemption under bounded concurrency','Prevent duplicate payment or checkout transactions']))
A(fam('race-inventory-balance','race-conditions','Inventory & balance','Double allocation and atomic balance or quota checks.',['WAPT-RACE-003','WAPT-RACE-004'],[DM,'Protect limited inventory from double allocation','Enforce balance and quota checks atomically']))
A(fam('race-tokens-authorization','race-conditions','Tokens & authorization','Atomic token consumption and state-plus-action authorization.',['WAPT-RACE-005','WAPT-RACE-006'],[DM,'Consume authentication and recovery tokens atomically','Authorize object state and action in one atomic operation']))
A(fam('race-workflow-idempotency','race-conditions','Workflow & idempotency','Optimistic or pessimistic transitions and atomic idempotency keys.',['WAPT-RACE-007','WAPT-RACE-008'],[DM,'Enforce workflow transitions under concurrency control','Bind idempotency keys atomically to caller, action, and body']))
A(fam('race-processing-construction','race-conditions','Processing & construction','File-processing publish races and partial object construction.',['WAPT-RACE-009','WAPT-RACE-010'],[DM,'Prevent file-processing and publish races','Prevent partial account or object construction']))
A(fam('race-technique','race-conditions','Technique','Synchronized delivery and adjacent-path retesting.',['WAPT-RACE-011','WAPT-RACE-012'],[DM,'Use synchronized race delivery without flooding','Verify race fixes under adjacent concurrency paths']))

# ---------------- client-side (31) ----------------
A(fam('client-dom-eval','client-side','DOM sources & evaluation','Source-to-sink tracing and dynamic evaluation of untrusted strings.',['WAPT-CLIENT-001','WAPT-CLIENT-002'],[DM,'Trace DOM sources to dangerous rendering sinks','Remove dynamic JavaScript evaluation of untrusted strings']))
A(fam('client-html-css','client-side','HTML & CSS injection','Non-script HTML injection and CSS injection or UI redressing.',['WAPT-CLIENT-003','WAPT-CLIENT-005'],[DM,'Assess non-script HTML injection with security impact','Constrain CSS injection and UI redressing']))
A(fam('client-redirect-resources','client-side','Redirects & resources','Client-side redirect destinations and resource URL manipulation.',['WAPT-CLIENT-004','WAPT-CLIENT-006'],[DM,'Allowlist client-side redirect destinations','Prevent client-side resource URL manipulation']))
A(fam('client-cors-framing','client-side','CORS & framing','Browser CORS behavior and clickjacking on sensitive pages.',['WAPT-CLIENT-007','WAPT-CLIENT-008'],[DM,'Verify CORS enforcement against actual client credential behavior','Prevent clickjacking on sensitive interactive pages']))
A(fam('client-postmessage','client-side','postMessage','Origin, source, and schema validation in both directions.',['WAPT-CLIENT-009','WAPT-CLIENT-010'],[DM,'Validate postMessage origins, sources, and schemas','Send replies only to validated exact origins']))
A(fam('client-storage','client-side','Browser storage','Sensitive data, untrusted input, and identity partitioning.',['WAPT-CLIENT-011','WAPT-CLIENT-012','WAPT-CLIENT-013'],[DM,'Keep sensitive data out of persistent browser storage','Treat storage as untrusted input','Partition IndexedDB by identity and tenant']))
A(fam('client-workers','client-side','Workers & channels','Service workers, Web Workers, and BroadcastChannel boundaries.',['WAPT-CLIENT-014','WAPT-CLIENT-015','WAPT-CLIENT-016','WAPT-CLIENT-017'],[DM,'Constrain service-worker scope and registration','Prevent stale private data in service-worker caches','Validate worker message boundaries','Isolate BroadcastChannel by application and account']))
A(fam('client-prototype-clobbering','client-side','Prototype pollution & DOM clobbering','Client merge setters, gadget tracing, and clobbered globals.',['WAPT-CLIENT-018','WAPT-CLIENT-019','WAPT-CLIENT-020'],[DM,'Prevent prototype pollution through client merge and path setters','Trace polluted properties into security gadgets','Prevent DOM clobbering of trusted variables and APIs']))
A(fam('client-navigation-boundaries','client-side','Navigation boundaries','window.name and reverse tabnabbing.',['WAPT-CLIENT-021','WAPT-CLIENT-022'],[DM,'Clear and validate window.name across navigation boundaries','Prevent reverse tabnabbing from external links']))
A(fam('client-supply-chain','client-side','Supply chain & inclusion','Third-party scripts, SRI, cross-site script inclusion, and source maps.',['WAPT-CLIENT-023','WAPT-CLIENT-024','WAPT-CLIENT-025','WAPT-CLIENT-026'],[DM,'Constrain third-party script execution and supply-chain scope','Apply SRI to stable cross-origin assets','Prevent cross-site script inclusion data disclosure','Review source maps without reporting readable client code']))
A(fam('client-secrets-authority','client-side','Secrets & authority','Client-bundle secrets, presentational authorization, and Web Crypto keys.',['WAPT-CLIENT-027','WAPT-CLIENT-028','WAPT-CLIENT-029'],[DM,'Remove secrets and privileged assumptions from client bundles','Keep client-side authorization strictly presentational','Use Web Crypto without exporting or hard-coding keys']))
A(fam('client-xsleaks-bfcache','client-side','XS-Leaks & bfcache','Cross-site leak channels and sensitive state resurfacing.',['WAPT-CLIENT-030','WAPT-CLIENT-031'],[DM,'Measure leak channels against two known states','Prevent sensitive pages resurfacing through bfcache or history']))

# ---------------- websocket (10) ----------------
A(fam('ws-transport','websocket','Transport','WSS enforcement and Origin allowlisting.',['WAPT-WS-001','WAPT-WS-002'],[DM,'Use WSS for every authenticated connection','Validate Origin against an exact allowlist']))
A(fam('ws-authentication','websocket','Authentication','Session establishment and token placement.',['WAPT-WS-003','WAPT-WS-004'],[DM,'Authenticate sessions explicitly and safely','Keep tokens out of URLs and logs']))
A(fam('ws-authorization','websocket','Authorization','Message-action and subscription authorization.',['WAPT-WS-005','WAPT-WS-006'],[DM,'Authorize every message action','Authorize subscriptions and object channels']))
A(fam('ws-messages-resources','websocket','Messages & resources','Schema validation and size, rate, and fan-out bounds.',['WAPT-WS-007','WAPT-WS-008'],[DM,'Validate message schemas and parser boundaries','Bound message size, rate, fan-out, and subscriptions']))
A(fam('ws-replay-lifecycle','websocket','Replay & lifecycle','Replay prevention and session-change reauthorization.',['WAPT-WS-009','WAPT-WS-010'],[DM,'Prevent message replay and duplicate side effects','Terminate and reauthorize sockets across session changes']))

# ---------------- security-headers (24) ----------------
A(fam('hdr-baseline','security-headers','Exposure baseline','Assessing headers against actual browser exposure.',['WAPT-HDR-001'],[DM,'Map every header to a demonstrated exposure before reporting']))
A(fam('hdr-hsts-csp','security-headers','HSTS & CSP','HSTS deployment and CSP enforcement with nonces, hashes, and navigation constraints.',['WAPT-HDR-002','WAPT-HDR-003','WAPT-HDR-004','WAPT-HDR-005'],[DM,'Deploy HSTS with a safe rollout and no mixed content','Match CSP to real script, font, and connect sources','Use unpredictable nonces or hashes without unsafe fallbacks','Constrain base-uri, object-src, and navigation destinations']))
A(fam('hdr-framing-mime','security-headers','Framing & MIME','Frame-ancestors, X-Frame-Options, nosniff, and content types.',['WAPT-HDR-006','WAPT-HDR-007','WAPT-HDR-008','WAPT-HDR-009'],[DM,'Prevent unauthorized framing with frame-ancestors','Keep X-Frame-Options consistent where retained','Send accurate Content-Type and charset on every body']))
A(fam('hdr-referrer-features','security-headers','Referrer & features','Referrer-Policy and Permissions-Policy.',['WAPT-HDR-010','WAPT-HDR-011'],[DM,'Limit referrer data to purpose-appropriate values','Restrict only the powerful features the page actually uses']))
A(fam('hdr-isolation','security-headers','Cross-origin isolation','COOP, COEP, and CORP decisions.',['WAPT-HDR-012','WAPT-HDR-013','WAPT-HDR-014'],[DM,'Use COOP only where window-opener hazards exist','Use COEP only when cross-origin isolation is required','Protect sensitive resources with CORP']))
A(fam('hdr-caching-downloads','security-headers','Caching & downloads','Cache-Control, Clear-Site-Data, and Content-Disposition.',['WAPT-HDR-015','WAPT-HDR-016','WAPT-HDR-017'],[DM,'Prevent sensitive browser caching with explicit Cache-Control','Use Clear-Site-Data deliberately during logout or reset','Set safe Content-Disposition for user-influenced downloads']))
A(fam('hdr-disclosure-obsolete','security-headers','Disclosure & obsolete headers','Version disclosure, X-XSS-Protection, HPKP, and Expect-CT.',['WAPT-HDR-018','WAPT-HDR-019','WAPT-HDR-020','WAPT-HDR-021'],[DM,'Minimize product and version disclosure headers','Disable obsolete X-XSS-Protection behavior','Do not deploy HPKP; treat Expect-CT as obsolete']))
A(fam('hdr-consistency','security-headers','Consistency','Route-level consistency, duplicates, and report-only handling.',['WAPT-HDR-022','WAPT-HDR-023','WAPT-HDR-024'],[DM,'Apply policies consistently across routes, errors, and redirects','Reject duplicate or malformed headers consistently','Distinguish report-only policies from enforced protection']))

# ---------------- cloud-storage (18) ----------------
A(fam('cloud-inventory-public','cloud-storage','Inventory & public access','Storage inventory and unintended public reads or listings.',['WAPT-CLOUD-001','WAPT-CLOUD-002','WAPT-CLOUD-003'],[DM,'Inventory buckets, identities, endpoints, and data classes','Prevent unintended public object reads','Prevent public bucket or container listing']))
A(fam('cloud-authorization','cloud-storage','Authorization','Tenant, owner, and purpose-scoped reads plus write constraints.',['WAPT-CLOUD-004','WAPT-CLOUD-005'],[DM,'Authorize reads by tenant, owner, and purpose','Constrain write, overwrite, and delete permissions']))
A(fam('cloud-signed-urls','cloud-storage','Signed URLs','Scoped downloads and constrained presigned uploads.',['WAPT-CLOUD-006','WAPT-CLOUD-007'],[DM,'Scope signed URLs to object, action, and lifetime','Constrain presigned uploads and shared access signatures']))
A(fam('cloud-cors','cloud-storage','Storage CORS','Browser origin and method configuration.',['WAPT-CLOUD-008'],[DM,'Configure storage CORS for intended origins and methods only']))
A(fam('cloud-metadata-credentials','cloud-storage','Metadata & credentials','Workload metadata blocking, credential leakage, least privilege, and cross-account trust.',['WAPT-CLOUD-009','WAPT-CLOUD-010','WAPT-CLOUD-011','WAPT-CLOUD-012'],[DM,'Block workload access to metadata credentials','Keep workload credentials out of responses and client artifacts','Apply least privilege to workload storage identities','Constrain cross-account and federated storage trust']))
A(fam('cloud-origin-tenant','cloud-storage','Origin & tenant isolation','CDN-protected endpoints and canonical tenant prefixes.',['WAPT-CLOUD-013','WAPT-CLOUD-014'],[DM,'Protect storage origins behind CDN or application controls','Isolate tenants with canonical prefixes and policy conditions']))
A(fam('cloud-lifecycle-events','cloud-storage','Lifecycle & events','Versioning, soft deletes, retention, and event consumers.',['WAPT-CLOUD-015','WAPT-CLOUD-016','WAPT-CLOUD-017'],[DM,'Control versions, soft deletes, and recovery access','Enforce lifecycle, retention, and legal-hold policy safely','Protect storage event notifications and consumers']))
A(fam('cloud-logging','cloud-storage','Logging','Access and policy-change logging without secret exposure.',['WAPT-CLOUD-018'],[DM,'Log storage access and policy changes without secrets']))

# ---------------- information-disclosure (18) ----------------
A(fam('info-errors-debug','information-disclosure','Errors & debug','Generic errors and disabled debug modes.',['WAPT-INFO-001','WAPT-INFO-002'],[DM,'Return generic errors without stack traces','Disable debug pages, REPLs, profilers, and toolbars']))
A(fam('info-secrets-maps','information-disclosure','Client secrets & maps','Client-delivered secrets and source-map content.',['WAPT-INFO-003','WAPT-INFO-004'],[DM,'Remove valid secrets from client-delivered assets','Review source maps for confidential source and data']))
A(fam('info-comments-files','information-disclosure','Comments & files','Sensitive comments and backup or temporary files.',['WAPT-INFO-005','WAPT-INFO-006'],[DM,'Remove sensitive comments, hidden fields, and disabled markup','Prevent publication of backups, swaps, and old deployments']))
A(fam('info-vcs-env','information-disclosure','VCS & environment files','Version-control metadata and environment configuration files.',['WAPT-INFO-007','WAPT-INFO-008'],[DM,'Block exposed repository metadata','Protect environment and deployment configuration files']))
A(fam('info-listing-versions','information-disclosure','Listing & versions','Directory listing and precise version disclosure.',['WAPT-INFO-009','WAPT-INFO-010'],[DM,'Disable directory and object-index listing','Minimize precise backend version disclosure']))
A(fam('info-operational-endpoints','information-disclosure','Operational endpoints','Health, metrics, tracing, and actuator exposure.',['WAPT-INFO-011'],[DM,'Protect operational endpoints from environment and data exposure']))
A(fam('info-api-log','information-disclosure','API & log disclosure','Sensitive data in errors and accessible logs.',['WAPT-INFO-012','WAPT-INFO-013'],[DM,'Prevent protected data in API error and validation responses','Keep secrets and personal data out of accessible logs']))
A(fam('info-cache-history','information-disclosure','Cache & history','Post-authentication cache and history exposure.',['WAPT-INFO-014'],[DM,'Prevent cache and history disclosure after authentication ends']))
A(fam('info-leads-personal','information-disclosure','Leads & personal data','Route-name leads and personal information exposure.',['WAPT-INFO-015','WAPT-INFO-016'],[DM,'Treat robots, sitemaps, and route names as leads','Limit email, username, and personnel exposure']))
A(fam('info-metadata-retest','information-disclosure','Metadata & retest','Document metadata and alternate-format remediation checks.',['WAPT-INFO-017','WAPT-INFO-018'],[DM,'Remove sensitive metadata from downloadable documents','Verify fixes across formats, caches, backups, and indexes']))

# ---------------- rate-limiting (12) ----------------
A(fam('rate-auth-abuse','rate-limiting','Authentication abuse','Guessing, stuffing, OTP, push, recovery, and registration limits.',['WAPT-RATE-001','WAPT-RATE-002','WAPT-RATE-003','WAPT-RATE-004','WAPT-RATE-005','WAPT-RATE-006'],[DM,'Bound guessing per account and contextual risk','Bound stuffing across distributed sources','Limit OTP and recovery-code attempts within lifetime','Prevent push-notification bombing','Limit reset and registration message flooding']))
A(fam('rate-resource-content','rate-limiting','Resource & content abuse','API budgets, search and export, uploads, and notification fan-out.',['WAPT-RATE-007','WAPT-RATE-008','WAPT-RATE-009','WAPT-RATE-010'],[DM,'Bound API requests by principal and operation cost','Limit search, scraping, pagination, and export extraction','Limit upload count, bytes, processing, and storage','Limit email, chat, and notification fan-out']))
A(fam('rate-commerce-bypass','rate-limiting','Commerce & bypass','Checkout abuse and client-controlled source identifiers.',['WAPT-RATE-011','WAPT-RATE-012'],[DM,'Limit payment, coupon, reservation, and checkout automation','Prevent client-controlled identifiers from bypassing limits']))

# ---------------- advanced (19) ----------------
A(fam('adv-cache-poisoning','advanced','Cache poisoning & deception','Unkeyed inputs, deception, key canonicalization, and CDN-origin parity.',['WAPT-ADV-001','WAPT-ADV-002','WAPT-ADV-003','WAPT-ADV-004'],[DM,'Poison through unkeyed inputs only where the cache actually stores them','Test deception with path and extension tricks on authenticated responses','Canonicalize cache keys across proxy and origin','Keep CDN and origin authorization behavior equivalent']))
A(fam('adv-deserialization','advanced','Deserialization','Java, Python, PHP, and .NET deserialization boundaries.',['WAPT-ADV-005','WAPT-ADV-006','WAPT-ADV-007','WAPT-ADV-008'],[DM,'Reject unsafe Java object deserialization','Reject untrusted pickle and equivalent formats','Prevent PHP unserialize object injection','Validate .NET formatters and ViewState integrity']))
A(fam('adv-parsing-coercion','advanced','Parsing & coercion','Duplicate JSON keys, URL parsing, type coercion, and signed-request canonicalization.',['WAPT-ADV-009','WAPT-ADV-010','WAPT-ADV-011','WAPT-ADV-012'],[DM,'Handle duplicate JSON keys consistently across boundaries','Align URL parsing across validators, clients, and browsers','Align numeric and type coercion across API layers','Canonicalize signed requests identically before verification']))
A(fam('adv-tenant-boundaries','advanced','Tenant & domain boundaries','Shared caches and custom-domain binding.',['WAPT-ADV-013','WAPT-ADV-014'],[DM,'Prevent cross-tenant leakage through shared caches and indexes','Bind custom domains and vanity hosts to verified tenants']))
A(fam('adv-integration-boundaries','advanced','Integration boundaries','Confused-deputy chains and webhook signature validation.',['WAPT-ADV-015','WAPT-ADV-016'],[DM,'Prevent confused-deputy access in service-to-service chains','Validate webhook signatures, timestamps, and replay state']))
A(fam('adv-chain-retest','advanced','Chain validation & retest','Least-impact chain validation and adjacent-path retesting.',['WAPT-ADV-017','WAPT-ADV-018'],[DM,'Validate chains with least-impact evidence at each edge','Retest fixes across protocol, parser, cache, and tenant paths']))
A(fam('adv-llm-boundary','advanced','LLM boundary','LLM prompt and tool-call authority.',['WAPT-ADV-019'],[DM,'Constrain LLM prompt and tool-call authority to the caller']))

# ---------------- ai-llm-security (11) ----------------
A(fam('ai-prompt-injection','ai-llm-security','Prompt injection','Direct and indirect instruction-boundary control.',['WAPT-AI-001','WAPT-AI-002'],[DM,'Test direct prompts against every connected tool and data scope','Deliver indirect instructions only through content you own end to end']))
A(fam('ai-prompt-retrieval-disclosure','ai-llm-security','Prompt & retrieval disclosure','System-prompt leakage and unauthorized retrieval.',['WAPT-AI-003','WAPT-AI-004'],[DM,'Compare disclosures against published documentation','Authorization-check every retrieved chunk before grounding']))
A(fam('ai-retrieval-poisoning','ai-llm-security','Retrieval poisoning','Corpus content steering other users.',['WAPT-AI-005'],[DM,'Use removable synthetic documents and verify effect removal']))
A(fam('ai-tool-call-security','ai-llm-security','Tool-call security','Generated arguments, excessive agency, and URL-fetching tools.',['WAPT-AI-006','WAPT-AI-007','WAPT-AI-010'],[DM,'Parameterize every interpreter call fed by model output','Authorize every consequential tool call at invocation time','Apply SSRF allowlists to model-invoked URL tools']))
A(fam('ai-output-handling','ai-llm-security','Output handling','Model output at rendering and parser sinks.',['WAPT-AI-008'],[DM,'Route model output through the same encoding and sanitization as user input']))
A(fam('ai-context-isolation','ai-llm-security','Context isolation','Cross-user and cross-tenant model context.',['WAPT-AI-009'],[DM,'Partition memory, sessions, and retrieval per account and tenant']))
A(fam('ai-resource-bounds','ai-llm-security','Resource bounds','Generation and tool-loop cost limits.',['WAPT-AI-011'],[DM,'Bound tokens, tool calls, and retrieval per principal and per call']))

doc = json.load(open('checklist/families.json'))
existing_ids = {f['id'] for f in doc['families']}
for f in F:
    assert f['id'] not in existing_ids, f['id']
    doc['families'].append(f)
json.dump(doc, open('checklist/families.json', 'w'), indent=2, ensure_ascii=False)
open('checklist/families.json', 'a').write('\n')
print('families total:', len(doc['families']))
